stages:
  - build
  #  - test
  - checkstyle
  - deploy

build:
  stage: build
  image: maven:3.8.1-openjdk-17-slim
  script:
    - mvn clean package

#test:
#  stage: test
#  image: maven:3.3.9-jdk-8
#  script:
#    - echo "Test DEMO app"
#    - mvn test && mvn jacoco:report
#    - cat target/site/jacoco/index.html | grep -o '.*'
#  coverage: "/Total.*?([0-9]{1,3})%/"


checkstyle:
  stage: checkstyle
  image: maven:3.8.1-openjdk-17-slim
  script:
    - echo "Checkstyle Energy Utility Platform app"
    - mvn checkstyle:check

variables:
  DB_IP: ec2-52-48-65-240.eu-west-1.compute.amazonaws.com
  DB_PORT: 5432
  DB_USER: wlryktxyqpyomt
  DB_PASSWORD: bee98a2afc7f0c3bcdd7df60ee7278ec5fa5cb4fb06a4039b1ffb1107d5851fd
  DB_DBNAME: devidei2vqv0v4

deploy:
  stage: deploy
  image: ruby:2.4
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=ds2021_energy_utlity_platform --api-key=$HEROKU_API_KEY
  only:
    - production
