stages:
  - build
  - test
  - checkstyle
  - deploy

build:
  stage: build
  image: maven:3.6.3-adoptopenjdk-11
  script:
    - mvn clean package

test:
  stage: test
  image: maven:3.6.3-adoptopenjdk-11
  script:
    - echo "Test EnergyUtilityPlatform app"
    - mvn test && mvn jacoco:report
    - cat target/site/jacoco/index.html | grep -o '.*'
  coverage: "/Total.*?([0-9]{1,3})%/"


checkstyle:
  stage: checkstyle
  image: maven:3.6.3-adoptopenjdk-11
  script:
    - echo "Checkstyle Energy Utility Platform app"
    - mvn checkstyle:check

variables:
  DB_IP: ec2-54-228-99-58.eu-west-1.compute.amazonaws.com
  DB_PORT: 5432
  DB_USER: wqpbyihwrpexor
  DB_PASSWORD: ae89f89167d391d2e2ef72e5f45d933a8d25382b7fa84ba5438f74e49644a00a
  DB_DBNAME: d1gutrkdpd57qh

deploy:
  stage: deploy
  image: ruby:2.4
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=ds2021energyutlityplatform --api-key=$HEROKU_API_KEY
  only:
    - production
